### ISSUE TITLE
客户端登录不上去

### ISSUE THREAD

**Issue by zhuzhh** [hezhongfeng/im-fe-admin#1]
https://im-client.hezf.online/login?stack-key=5220269b

![image](https://user-images.githubusercontent.com/41102272/93752536-649f9b00-fc31-11ea-840d-7f3d564e07bc.png)

不具备登录权限

**Comment by hezhongfeng** [comment]
有人把所有角色的登录权限给下了，我找时间看看弄回来

**Comment by hezhongfeng** [comment]
角色已经被删除了，所以我把数据库重置了，你新建个账号吧
